// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Nov 20 21:30:11 2009

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/timer.h>

#include "plot.h"
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef GRAPHTEST_H
#define GRAPHTEST_H


// begin wxGlade: ::extracode
// end wxGlade

class ROSTimer : public wxTimer
{
public:
    void Notify();
    void start();
};

class MainFrame: public wxFrame {
public:
    // begin wxGlade: MainFrame::ids
    // end wxGlade

    MainFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

	virtual void OnPaint(wxPaintEvent &event);
    // begin wxGlade: MainFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

	Plot thePlot;
    // begin wxGlade: MainFrame::attributes
    wxStaticBox* sizer_1_staticbox;
    wxPanel* graphPanel;
    // end wxGlade

protected:
    DECLARE_EVENT_TABLE()
}; // wxGlade: end class

BEGIN_EVENT_TABLE(MainFrame, wxFrame)
	EVT_PAINT(MainFrame::OnPaint)
END_EVENT_TABLE();

#endif // GRAPHTEST_H
